language: go

go:
  - go1.7
  - go1.8
  - tip

install:
  - go get -u github.com/campoy/embedmd
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/kisielk/errcheck
script:
  - embedmd -d **/*.md
  - bash .gofmt.travis.sh
  - go list ./... | grep -v vendor | xargs go test
  - go list ./... | grep -v vendor | xargs golint
  - go list ./... | grep -v "vendor\|errcheck" | xargs errcheck
  # this should be removed once https://github.com/golang/go/issues/23395 is fixed
  - go version | grep devel > /dev/null || go list ./... | grep -v vendor | xargs go vet
